# Generated by Django 5.1.7 on 2025-03-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
