# Generated by Django 5.1.7 on 2025-03-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
