# Generated by Django 5.1.7 on 2025-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_alter_employer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
