# Generated by Django 5.1.7 on 2025-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_employer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
