# Generated by Django 5.1.7 on 2025-03-13 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_alter_employer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=50)),
                ('reports_to', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=255)),
                ('application_deadline', models.DateField()),
                ('skills', models.TextField()),
                ('posting_date', models.DateField(default=django.utils.timezone.now)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employer')),
            ],
        ),
    ]
