# Generated by Django 5.1.7 on 2025-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='details',
            field=models.TextField(default='job post is here'),
            preserve_default=False,
        ),
    ]
