# Generated by Django 5.1.7 on 2025-03-16 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.jobposting')),
            ],
        ),
    ]
