# Generated by Django 5.1.7 on 2025-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_jobtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='approved',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='active',
            field=models.CharField(default='yes', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='approved',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
