# Generated by Django 5.1.7 on 2025-05-10 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_blogpost_approved_employer_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.jobposting')),
            ],
        ),
    ]
