# Generated by Django 5.1.7 on 2025-05-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_candidatetestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestresult',
            name='obtained_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatetestresult',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
