# Generated by Django 5.1.7 on 2025-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
