# Generated by Django 5.1.7 on 2025-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='selected_theme',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
